<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
{$dailyBalance = sprintf('%01.2f', $totalBalance/$daysLeft)}

	<nav class="navbar navbar-default">
	  <div class="container">
		<ul class="nav navbar-nav nav-tabs">
		  <li {$budgetLiClass}><a href="{$thisScript}">Budget</a></li>
		  <li {$summaryLiClass}><a href="{$thisScript}?verb=summary">Summary</a></li>
		  <li><a href="#" data-toggle="modal" data-target="#newLedgerModal">New Transaction</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li><a href='#'>${$dailyBalance}/day for {$daysLeft} days</a></li>
		</ul>
	  </div>
	</nav>

	<div class="container">
		{$this->renderContent()}
	</div>


<div id="newLedgerModal" class="modal" role="dialog">
  <div class="modal-dialog modal-sm">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Transaction</h4>
      </div>
      <div class="modal-body">
        <form class="form" role="form" id="modalForm" action="{$thisScript}" method="POST">
            <input type="hidden" name="verb" value="create">
			<label class="radio-inline"><input type="radio" name="credit" checked value=0>Debit</label>
			<label class="radio-inline"><input type="radio" name="credit" value=1>Credit</label>
            <div class="form-group">
                <label for="description">description</label>
                <input type="text" class="form-control" name="description">
            </div>
            <div class="form-group">
                <label for="amount">amount</label>
                <input type="text" class="form-control" name="amount">
            </div>
            <input type="submit" class="form-control" value="OK">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>
