<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>My Budget</title>
<meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
<script type="text/javascript">
  <!--
  function makeHttpRequest(blah, callback_function, return_xml) {
    var url = "{$thisScript]";
    var http_request, response, i;

    var activex_ids = [
      'MSXML2.XMLHTTP.3.0',
      'MSXML2.XMLHTTP',
      'Microsoft.XMLHTTP'
    ];

    if (window.XMLHttpRequest) { // Mozilla, Safari, IE7+...
      http_request = new XMLHttpRequest();
      if (http_request.overrideMimeType) {
        http_request.overrideMimeType('text/xml');
      }
    } else if (window.ActiveXObject) { // IE6 and older
      for (i = 0; i < activex_ids.length; i++) {
        try {
          http_request = new ActiveXObject(activex_ids[i]);
        } catch (e) {}
      }
    }

    if (!http_request) {
      alert('Unfortunatelly you browser doesn\'t support this feature.');
      return false;
    }

    http_request.onreadystatechange = function() {
      if (http_request.readyState !== 4) {
          // not ready yet
          return;
      }
      if (http_request.status !== 200) {
        // ready, but not OK
        alert('There was a problem with the request.(Code: ' +
              http_request.status + ')');
        return;
      }

      if (return_xml) {
        response = http_request.responseXML;
      } else {
        response = http_request.responseText;
      }
/*
      callback_function(response);

      document.getElementById('ajax-response').innerHTML =
              http_request.responseText;
      document.getElementById('ajax-response').className = "header1 red";
      if (http_request.responseText == "Email Sent") {
        setTimeout("hideit('email');",2000);
      }
*/
    };

    http_request.open('GET', url, true);
    http_request.send(null);
    return false;
  }
  function hideit(element) {
    elem = document.getElementById(element);
    elem.className = "hideme";
    return false;
  }
  function confirmDeletion(id,descript) {
    delurl = "{$thisScript}?verb=delete&id=" + id;
    var response = confirm("You're deleting \"" + descript + "\".  OK?!?");
    if (response) {
      window.location = delurl;
    }
    else {
      return false;
    }
  }
  function editTrans(id,amount,descript) {
    clr = document.getElementById('clr');
    clr.checked = false;
    ID = document.getElementById('id');
    ID.value = id;
    desc = document.getElementById('desc');
    desc.value = descript;
    amt = document.getElementById('amt');
    amt.value = amount;
    elem = document.getElementById('editor');
    elem.className = 'showme';
  }
  // -->
</script>
<style type="text/css">
<!--
  div.showme {
/*
    visibility:visible;
*/
    position:absolute;
    display:block;
    top:30px;
    left:10px;
    width:260px;
    height:250px;
    background-color:#7EB0DE;
    margin:5px;
    padding:10px;
    border: 2px solid #000000;
    z-index:10;
  }
  div.hideme {
    display:none;
    position:fixed;
    z-index:0;
  }
  a:link { color:red; }
  .nav {
    font-size:16pt;
  }
  a.nav { color:red; }
  div.nav { float:right; font-size:11pt; padding:6px 0 0; }
-->
</style>
</head>
<body>
<div class='hideme' id='editor'>
<form action='{$thisScript}' method='POST'>
  <input type="hidden" name="id" id="id" value=""><br>
  <input type="hidden" name="verb" value="update"><br>
  <table align='center'>
  <tr>
    <td>description</td>
    <td><input size='15' type="text" name="description" id="desc" value=""></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td>amount</td>
    <td><input size='8' type="text" name="amount" id="amt" value=""></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td><label for="clr">cleared?</label></td>
    <td><input type="checkbox" name="cleared" id="clr" value='1'></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td><input type="submit" value="OK"></td>
    <td align='right'>
      <input type="submit" value="Cancel" onClick="return hideit('editor');">
    </td>
  </tr>
  </table>
</form>
</div>

<table width='100%' align='center' border='0' cellpadding='0' cellspacing='0'>
  <tr height=30>
    <td colspan=4 valign='top'>
      <a class='nav' href='{$thisScript}'>Budget</a> <span class='nav'>|</span>
      <a class='nav' href='{$thisScript}?verb=summary'>Summary</a>
      <div class='nav'>
{$dailyBalance = sprintf('%01.2f', $totalBalance/$daysLeft)}
${$dailyBalance}/day for {$daysLeft} days
      </div>
    </td>
  </tr>
{$this->renderContent()}
</table>
</body>
</html>

