<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>My Budget</title>
<meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
<script type='text/javascript' src='js/ledger.js'></script>
<link type='text/css' rel='stylesheet' href='css/ledger.css'>
</head>
<body>
<div class='hideme' id='editor'>
<form action='{$thisScript}' method='POST'>
  <input type="hidden" name="id" id="id" value=""><br>
  <input type="hidden" name="verb" value="update"><br>
  <table align='center'>
  <tr>
    <td>description</td>
    <td><input size='15' type="text" name="description" id="desc" value=""></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td>amount</td>
    <td><input size='8' type="text" name="amount" id="amt" value=""></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td><label for="clr">cleared?</label></td>
    <td><input type="checkbox" name="cleared" id="clr" value='1'></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td><input type="submit" value="OK"></td>
    <td align='right'>
      <input type="submit" value="Cancel" onClick="return hideit('editor');">
    </td>
  </tr>
  </table>
</form>
</div>

<table width='100%' align='center' border='0' cellpadding='0' cellspacing='0'>
  <tr height=30>
    <td colspan=4 valign='top'>
      <a class='nav' href='{$thisScript}'>Budget</a> <span class='nav'>|</span>
      <a class='nav' href='{$thisScript}?verb=summary'>Summary</a>
      <div class='nav'>
{$dailyBalance = sprintf('%01.2f', $totalBalance/$daysLeft)}
${$dailyBalance}/day for {$daysLeft} days
      </div>
    </td>
  </tr>
{$this->renderContent()}
</table>
</body>
</html>

