<div class="row text-center">
	<ul class="list-inline">
	{foreach $durationDescriptions as $durationString => $durationValue}
		{if $durationValue == $duration}
		<li>{$durationString}</li>
		{else}
		<li><a href="{$thisScript}?verb=summary&duration={$durationValue}">{$durationString}</a></li>
		{/if}
	{/foreach}
	</ul>
</div>

{foreach $transactionGroups as $transactionGroup}
	{$from = $transactionGroup->startDate}
	{$to = $transactionGroup->endDate}
	{$debitSum = $transactionGroup->debitSum}
	{$creditSum = $transactionGroup->creditSum}

<table class="table table-striped">
	<tr class="success">
		<th>
			<i>{$from} - {$to}</i>
		</th>
		<th>&nbsp;</th>
		<th class="text-right">
			<i>${$creditSum}</i>
		</th>
	</tr>

	{$i = 1}
	{foreach $transactionGroup->transactions as $t}
		{if $i%2}
			{$bgcolor = 'bg-info'}
		{else}
			{$bgcolor = ''}
		{/if}
	<tr>
		<td class="col-xs-6">{$t->description}</td>

		<td class="col-xs-2"><em>{$t->percent}%</em></td>

		<td class="col-xs-4 text-right">
		{if !$t->description}
			<b>${$t->amount}</b>
		{else}
			${$t->amount}
		{/if}
		</td>
	</tr>
			{$i++}
		{/foreach}
	<tr class="info">
		<td><i>Total Debits</i></td>
		<td>&nbsp;</td>
		<td class="text-right"><b>${$debitSum}</b></td>
	</tr>
</table>

{/foreach}
