{if $unclearedAmount}
<div class="row">
	<div class="col-xs-6 pull-right text-right">
		<strong><em>${$unclearedAmount} uncleared</em></strong>
	</div>
</div>
{/if}

<div class="row">
	<div class="col-xs-7">
	&nbsp;
	</div>
	<div class="col-xs-5">
	<span>
	<i>amount</i>
	</span>
	<span class="pull-right text-right">
	<i>balance</i>
	</span>
	</div>
</div>

{if $transactions}
{foreach $transactions as $index => $t}
	{$balance = sprintf('%01.2f',$t->balance)}
	{if $t->balance > 0}
		{$bgcolor = ''}
	{else}
		{$bgcolor = 'bg-danger'}
	{/if}
<div class="row {$bgcolor}">
	<div class="col-xs-7">
	<span class='glyphicon glyphicon-trash'></span>
	{$t->description} ({$t->tshort})
	</div>

	<div class="col-xs-5">
	<span>
	{if $t->credit}
	${$t->amount}
	{else}
		{if !$t->cleared}
	<a href='#' data-toggle="modal" data-target="#ledgerModal">(${$t->amount})</a>
		{else}
	(${$t->amount})
		{/if}
	{/if}
	</span>

	<span class="pull-right text-right">
	{if !$index}
	<b>${$balance}</b>
	{else}
	${$balance}
	{/if}
	</span>
	</div>
</div>
{/foreach}
{/if}

{if $unclearedTransactions}
{foreach $unclearedTransactions as $index => $t}
<div class="row">
	<div class="col-xs-4">
	{$t->description} ({$t->tshort})
	</div>

	<div class="col-xs-4">
	<a href='#' onClick="return editTrans('{$t->id}', '{$t->amount}', '{$t->description}');">(${$t->amount})</a>
	</div>

	<div class="col-xs-4 text-right">
	OLD
	</div>
</div>
{/foreach}
{/if}

<div id="ledgerModal" class="modal" role="dialog">
  <div class="modal-dialog modal-sm">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modify Transaction</h4>
      </div>
      <div class="modal-body">
		<form class="form" role="form" id="modalForm" action="{$thisScript}" method="POST">
			<input type="hidden" name="verb" value="update">
			<input type="hidden" name="id" value="">
			<div class="form-group">
				<label for="description">description</label>
				<input type="text" class="form-control" name="description">
			</div>
			<div class="form-group">
				<label for="amount">amount</label>
				<input type="text" class="form-control" name="amount">
			</div>
			<div class="checkbox">
				<label for="cleared"><input type="checkbox" value="1">Cleared?</label>
			</div>
			<input type="submit" class="form-control" value="OK">
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
