<div class="row text-center">
	<ul class="list-inline">
	{foreach $durationDescriptions as $durationString => $durationValue}
		{if $durationValue == $duration}
		<li class="list-inline-item">{$durationString}</li>
		{else}
		<li class="list-inline-item"><a href="{$thisScript}?verb=summary&duration={$durationValue}">{$durationString}</a></li>
		{/if}
	{/foreach}
	</ul>
</div>

{foreach $transactionGroups as $transactionGroup}
	{$from = $transactionGroup->startDate}
	{$to = $transactionGroup->endDate}
	{$debitSum = $transactionGroup->debitSum}
	{$creditSum = $transactionGroup->creditSum}

<table class="table table-striped">
	<tr class="table-success">
		<th>
			<i>{$from} - {$to}</i>
		</th>
		<th>&nbsp;</th>
		<th class="text-end">
			<i>${$creditSum}</i>
		</th>
	</tr>

	{foreach $transactionGroup->transactions as $t}
	<tr>
		<td class="col-6">{$t->description}</td>

		<td class="col-2"><em>{$t->percent}%</em></td>

		<td class="col-4 text-end">
		{if !$t->description}
			<b>${$t->amount}</b>
		{else}
			${$t->amount}
		{/if}
		</td>
	</tr>
		{/foreach}
	<tr class="table-danger">
		<td><i>Total Debits</i></td>
		<td>&nbsp;</td>
		<td class="text-end"><b>${$debitSum}</b></td>
	</tr>
</table>

{/foreach}
