<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<h4 class="modal-title">Delete Transaction</h4>
</div>
<div class="modal-body">
	<p class="alert alert-danger">Are you sure you want to delete this transaction?</p>
	<form class="form" role="form" id="modalForm" action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="delete">
		<input type="hidden" name="id" value="{$id}">
		<div class="form-group">
			<label for="description">description</label>
			<input type="text" class="form-control" value="{$description}" readonly>
		</div>
		<div class="form-group">
			<label for="amount">amount</label>
			<input type="text" class="form-control" value="{$amount}" readonly>
		</div>
		<div class="form-group">
			<label for="time">timestamp</label>
			<input type="text" class="form-control" value="{$time}" readonly>
		</div>
		<input type="submit" class="form-control btn-primary" value="OK">
	</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

