<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<h4 class="modal-title">Delete Transaction</h4>
</div>
<div class="modal-body">
	<p>Are you sure you want to delete this transaction?</p>
	<p><b>"{$description}" for ${$amount}</b></p>
	<p>{$time}</p>
	<form class="form" role="form" id="modalForm" action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="delete">
		<input type="hidden" name="id" value="{$id}">
		<input type="submit" class="form-control" value="OK">
	</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

