{if $transactions}
{foreach $transactions as $t}
	{$balance = number_format($t->balance, 2)}
	{if $t->balance <= 0}
		{$context = 'class="danger"'}
	{elseif !$t->cleared && !$t->credit}
		{$context = 'class="info"'}
	{elseif $t->credit}
		{$context = 'class="success"'}
	{else}
		{$context = ''}
	{/if}
<tr {$context}>
	<td>
		<a href="{$thisScript}?verb=deleteModal&id={$t->id}" data-toggle="modal" data-target="#deleteModal"><span class='glyphicon glyphicon-trash'></span></a>
	</td>

	<td>
		{$t->tshort}
	</td>

	<td>
		{$t->description}
	</td>

	<td>
	{if $t->credit}
		${$t->amount}
	{elseif $t->cleared}
		(${$t->amount})
	{else}
		<a href="{$thisScript}?verb=updateModal&id={$t->id}" data-toggle="modal" data-target="#updateModal">(${$t->amount})</a>
	{/if}
	</td>

	<td class="text-right">
	${$balance}
	</td>
</tr>
{/foreach}
{/if}

{if $unclearedTransactions}
{foreach $unclearedTransactions as $t}
<tr class="warning uncleared">
	<td>
		<a href="{$thisScript}?verb=deleteModal&id={$t->id}" data-toggle="modal" data-target="#deleteModal"><span class='glyphicon glyphicon-trash'></span></a>
	</td>

	<td>
		{$t->tshort}
	</td>

	<td>
		{$t->description}
	</td>

	<td>
		<a href="{$thisScript}?verb=updateModal&id={$t->id}" data-toggle="modal" data-target="#updateModal">(${$t->amount})</a>
	</td>

	<td class="text-right">OLD</td>
</tr>
{/foreach}
{/if}
<tr class='mutable'>
	<td colspan=5>
		<button id="moreTransactions" nextwindowend="{$nextWindowEnd}" type="button" class="btn btn-secondary btn-lg btn-block">Load more</button>
	</td>
</tr>
<script type="text/javascript">
<!--
bindMoreTransactionsClick();
-->
</script>
