{if $transactions}
{foreach $transactions as $t}
	{if $t->balance <= 0}
		{$context = 'class="danger"'}
	{elseif !$t->cleared && !$t->credit}
		{$context = 'class="info"'}
	{elseif $t->credit}
		{$context = 'class="success"'}
	{else}
		{$context = ''}
	{/if}
<tr {$context}>
	<td>
		<a href="{$thisScript}?verb=deleteModal&id={$t->id}" data-toggle="modal" data-target="#deleteModal"><span class='glyphicon glyphicon-trash'></span></a>
	</td>

	<td>
		{$t->tshort}
	</td>

	<td>
		{$t->description}
	</td>

	<td>
    {if !$t->credit && !$t->cleared}
        <a href="{$thisScript}?verb=updateModal&id={$t->id}" data-toggle="modal" data-target="#updateModal">{$t->formattedAmount}</a>
    {else}
        {$t->formattedAmount}
    {/if}
	</td>

	<td class="text-right">
        {$t->formattedBalance}
	</td>
</tr>
{/foreach}
{/if}

{if $unclearedTransactions}
{foreach $unclearedTransactions as $t}
<tr class="warning uncleared">
	<td>
		<a href="{$thisScript}?verb=deleteModal&id={$t->id}" data-toggle="modal" data-target="#deleteModal"><span class='glyphicon glyphicon-trash'></span></a>
	</td>

	<td>
		{$t->tshort}
	</td>

	<td>
		{$t->description}
	</td>

	<td>
		<a href="{$thisScript}?verb=updateModal&id={$t->id}" data-toggle="modal" data-target="#updateModal">{$t->formattedAmount}</a>
	</td>

	<td class="text-right">OLD</td>
</tr>
{/foreach}
{/if}
<tr class='mutable'>
	<td colspan=5>
		<button id="moreTransactions" nextwindowend="{$nextWindowEnd}" type="button" class="btn btn-secondary btn-lg btn-block">Load more</button>
	</td>
</tr>
<script type="text/javascript">
<!--
bindMoreTransactionsClick();
-->
</script>
