<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<h4 class="modal-title">Modify Transaction</h4>
</div>
<div class="modal-body">
	<form class="form" role="form" id="modalForm" action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="update">
		<input type="hidden" name="id" value="{$id}">
		<div class="form-group">
			<label for="description">description</label>
			<input type="text" class="form-control" name="description" value="{$description}">
		</div>
		<div class="form-group">
			<label for="amount">amount</label>
			<input type="text" class="form-control" name="amount" value="{$amount}">
		</div>
		<div class="checkbox">
			{if $cleared}
			<label for="cleared"><input name="cleared" type="checkbox" value="1" checked>Cleared?</label>
			{else}
			<label for="cleared"><input name="cleared" type="checkbox" value="1">Cleared?</label>
			{/if}
		</div>
		<input type="submit" class="form-control" value="OK">
	</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
