<div class="modal-header">
	<h5 class="modal-title">Modify Transaction</h5>
	<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
	<form id="updateForm" action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="{$verbUpdate}">
		<input type="hidden" name="id" value="{$id}">
		<div class="form-floating mb-3">
			<input type="text" class="form-control" id="description" name="description" placeholder="description" value="{$description}">
			<label for="description">description</label>
		</div>
		<div class="form-floating mb-3">
			<input type="text" class="form-control" id="amount" name="amount" placeholder="amount" value="{$amount}">
			<label for="amount">amount</label>
		</div>
		<div class="form-floating mb-3">
			<input type="text" class="form-control" id="timestamp" placeholder="timestamp" value="{$time}" readonly>
			<label for="timestamp">timestamp</label>
		</div>
		<div class="d-grid mb-4">
		{if $cleared}
			<input type="checkbox" class="btn-check" name="cleared" id="cleared" value="1" checked autocomplete="off">
		{else}
			<input type="checkbox" class="btn-check" name="cleared" id="cleared" value="1" autocomplete="off">
		{/if}
			<label class="btn btn-outline-success" for="cleared">Cleared?</label>
		</div>
	</form>
	<form id="deleteForm" action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="{$verbDelete}">
		<input type="hidden" name="id" value="{$id}">
	</form>
</div>
<div class="modal-footer justify-content-between">
	<button type="button" class="btn btn-outline-danger" onclick="if(confirm('Delete this transaction?')) document.getElementById('deleteForm').submit()">Delete</button>
	<div>
		<button type="submit" form="updateForm" class="btn btn-primary me-2">OK</button>
		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	</div>
</div>
