<div class="modal-header">
	<h5 class="modal-title">Modify Transaction</h5>
	<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
	<form action="{$thisScript}" method="POST">
		<input type="hidden" name="verb" value="update">
		<input type="hidden" name="id" value="{$id}">
		<div class="mb-3">
			<label for="description">description</label>
			<input type="text" class="form-control" name="description" placeholder="description" value="{$description}">
		</div>
		<div class="mb-3">
			<label for="amount">amount</label>
			<input type="text" class="form-control" name="amount" placeholder="amount" value="{$amount}">
		</div>
		<div class="mb-3">
			<label for="amount">timestamp</label>
			<input type="text" class="form-control" value="{$time}" readonly>
		</div>
		<div class="mb-3">
			<div class="form-check form-check-inline">
			{if $cleared}
				<input class="form-check-input" name="cleared" type="checkbox" id="cleared" value="1" checked>
			{else}
				<input class="form-check-input" name="cleared" type="checkbox" id="cleared" value="1">
			{/if}
			<label class="form-check-label" for="cleared">Cleared?</label>
			</div>
		</div>
		<button type="submit" class="btn btn-primary w-100">OK</button>
	</form>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>
